spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enable: true

envio:
  email:
    remetente:
    nomeRementente: 'javanauta'

server:
  port: 8082